// This file is auto-generated from the EventTypes.json file
// Do not edit this file directly

export interface EventType {
  id: string;
  displayName: string;
  description: string;
  application: string;
  headerSchema: SchemaField[];
  bodySchema: SchemaField[];
}

export interface SchemaField {
  name: string;
  type: string;
  description?: string;
}

export interface EventTypesByApplication {
  [application: string]: EventType[];
}

export const eventTypes: EventType[] = [
  {
    id: 'AllocationCreated',
    displayName: 'Allocation Created',
    description:
      'An event of this type is fired whenever an AllocationCreated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'date',
        type: 'DateTime',
      },
      {
        name: 'instrumentIdentifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'AllocationDeleted',
    displayName: 'Allocation Deleted',
    description:
      'An event of this type is fired whenever an AllocationDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
    ],
  },
  {
    id: 'AllocationUpdated',
    displayName: 'Allocation Updated',
    description:
      'An event of this type is fired whenever an AllocationUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'date',
        type: 'DateTime',
      },
      {
        name: 'instrumentIdentifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'ConstituentsUpdated',
    displayName: 'Constituents Updated',
    description:
      'An event of this type is fired whenever a ConstituentsUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'effectiveFrom',
        type: 'DateTime',
      },
    ],
  },
  {
    id: 'FileContentVirusScanCompleted',
    displayName: 'File Content Virus Scan Completed',
    description:
      'An event of this type is fired whenever a FileContentVirusScanCompleted event is created in Drive',
    application: 'Drive',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'fileId',
        type: 'String',
      },
      {
        name: 'folderId',
        type: 'String',
      },
      {
        name: 'filePath',
        type: 'String',
      },
      {
        name: 'fileName',
        type: 'String',
      },
      {
        name: 'status',
        type: 'String',
      },
      {
        name: 'statusDetail',
        type: 'String',
      },
    ],
  },
  {
    id: 'FileCreated',
    displayName: 'File Created',
    description:
      'An event of this type is fired whenever a FileCreated event is created in Drive',
    application: 'Drive',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'fileId',
        type: 'String',
      },
      {
        name: 'folderId',
        type: 'String',
      },
      {
        name: 'filePath',
        type: 'String',
      },
      {
        name: 'fileName',
        type: 'String',
      },
      {
        name: 'status',
        type: 'String',
      },
      {
        name: 'statusDetail',
        type: 'String',
      },
    ],
  },
  {
    id: 'FileDeleted',
    displayName: 'File Deleted',
    description:
      'An event of this type is fired whenever a FileDeleted event is created in Drive',
    application: 'Drive',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'fileId',
        type: 'String',
      },
      {
        name: 'folderId',
        type: 'String',
      },
      {
        name: 'filePath',
        type: 'String',
      },
      {
        name: 'fileName',
        type: 'String',
      },
      {
        name: 'status',
        type: 'String',
      },
      {
        name: 'statusDetail',
        type: 'String',
      },
    ],
  },
  {
    id: 'FileMetadataUpdated',
    displayName: 'File Metadata Updated',
    description:
      'An event of this type is fired whenever a FileMetadataUpdated event is created in Drive',
    application: 'Drive',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'fileId',
        type: 'String',
      },
      {
        name: 'folderId',
        type: 'String',
      },
      {
        name: 'filePath',
        type: 'String',
      },
      {
        name: 'fileName',
        type: 'String',
      },
      {
        name: 'status',
        type: 'String',
      },
      {
        name: 'statusDetail',
        type: 'String',
      },
    ],
  },
  {
    id: 'FolderCreated',
    displayName: 'Folder Created',
    description:
      'An event of this type is fired whenever a FolderCreated event is created in Drive',
    application: 'Drive',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'folderId',
        type: 'String',
      },
      {
        name: 'folderPath',
        type: 'String',
      },
      {
        name: 'folderName',
        type: 'String',
      },
    ],
  },
  {
    id: 'FolderDeleted',
    displayName: 'Folder Deleted',
    description:
      'An event of this type is fired whenever a FolderDeleted event is created in Drive',
    application: 'Drive',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'folderId',
        type: 'String',
      },
      {
        name: 'folderPath',
        type: 'String',
      },
      {
        name: 'folderName',
        type: 'String',
      },
    ],
  },
  {
    id: 'FolderMetadataUpdated',
    displayName: 'Folder Metadata Updated',
    description:
      'An event of this type is fired whenever a FolderMetadataUpdated event is created in Drive',
    application: 'Drive',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'folderId',
        type: 'String',
      },
      {
        name: 'folderPath',
        type: 'String',
      },
      {
        name: 'folderName',
        type: 'String',
      },
    ],
  },
  {
    id: 'HoldingAdjustmentCreated',
    displayName: 'Holding Adjustment Created',
    description:
      'An event of this type is fired whenever a HoldingAdjustmentCreated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'effectiveAt',
        type: 'DateTime',
      },
    ],
  },
  {
    id: 'HoldingAdjustmentDeleted',
    displayName: 'Holding Adjustment Deleted',
    description:
      'An event of this type is fired whenever a HoldingAdjustmentDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'effectiveAt',
        type: 'DateTime',
      },
    ],
  },
  {
    id: 'HoldingAdjustmentUpdated',
    displayName: 'Holding Adjustment Updated',
    description:
      'An event of this type is fired whenever a HoldingAdjustmentUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'effectiveAt',
        type: 'DateTime',
      },
      {
        name: 'instrumentIdentifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'InstrumentCreated',
    displayName: 'Instrument Created',
    description:
      'An event of this type is fired whenever an InstrumentCreated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'lusidInstrumentId',
        type: 'String',
      },
      {
        name: 'identifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'InstrumentDeleted',
    displayName: 'Instrument Deleted',
    description:
      'An event of this type is fired whenever an InstrumentDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'lusidInstrumentId',
        type: 'String',
      },
      {
        name: 'identifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'InstrumentUpdated',
    displayName: 'Instrument Updated',
    description:
      'An event of this type is fired whenever an InstrumentUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'lusidInstrumentId',
        type: 'String',
      },
      {
        name: 'identifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'IntegrationRunEnded',
    displayName: 'Integration Run Ended',
    description:
      'An event of this type is fired whenever an IntegrationRunEnded event is created in Integrations',
    application: 'Integrations',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'runId',
        type: 'String',
      },
      {
        name: 'instanceId',
        type: 'String',
      },
      {
        name: 'integrationName',
        type: 'String',
      },
      {
        name: 'integrationType',
        type: 'String',
      },
      {
        name: 'status',
        type: 'String',
      },
    ],
  },
  {
    id: 'JobDidNotStart',
    displayName: 'Job Did Not Start',
    description:
      'An event of this type is fired whenever a JobDidNotStart event is created in Scheduler',
    application: 'Scheduler',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scheduleScope',
        type: 'String',
      },
      {
        name: 'scheduleCode',
        type: 'String',
      },
      {
        name: 'jobScope',
        type: 'String',
      },
      {
        name: 'jobCode',
        type: 'String',
      },
      {
        name: 'runId',
        type: 'String',
      },
    ],
  },
  {
    id: 'JobFailed',
    displayName: 'Job Failed',
    description:
      'An event of this type is fired whenever a JobFailed event is created in Scheduler',
    application: 'Scheduler',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scheduleScope',
        type: 'String',
      },
      {
        name: 'scheduleCode',
        type: 'String',
      },
      {
        name: 'jobScope',
        type: 'String',
      },
      {
        name: 'jobCode',
        type: 'String',
      },
      {
        name: 'runId',
        type: 'String',
      },
    ],
  },
  {
    id: 'JobSucceeded',
    displayName: 'Job Succeeded',
    description:
      'An event of this type is fired whenever a JobSucceeded event is created in Scheduler',
    application: 'Scheduler',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scheduleScope',
        type: 'String',
      },
      {
        name: 'scheduleCode',
        type: 'String',
      },
      {
        name: 'jobScope',
        type: 'String',
      },
      {
        name: 'jobCode',
        type: 'String',
      },
      {
        name: 'runId',
        type: 'String',
      },
    ],
  },
  {
    id: 'LegalEntityCreated',
    displayName: 'Legal Entity Created',
    description:
      'An event of this type is fired whenever a LegalEntityCreated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'identifiers',
        type: 'CollectionOfIdentifiers',
      },
      {
        name: 'lusidLegalEntityId',
        type: 'String',
      },
    ],
  },
  {
    id: 'LegalEntityDeleted',
    displayName: 'Legal Entity Deleted',
    description:
      'An event of this type is fired whenever a LegalEntityDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'identifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'LegalEntityUpdated',
    displayName: 'Legal Entity Updated',
    description:
      'An event of this type is fired whenever a LegalEntityUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'identifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'Manual',
    displayName: 'Manual event',
    description:
      'Events of this type can be triggered manually by posting to the Trigger Manual Event API endpoint',
    application: 'Notification Service',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
    ],
    bodySchema: [
      {
        name: 'subject',
        type: 'String',
      },
      {
        name: 'message',
        type: 'DateTime',
      },
      {
        name: 'jsonMessage',
        type: 'JsonObject',
      },
    ],
  },
  {
    id: 'OrderCreated',
    displayName: 'Order Created',
    description:
      'An event of this type is fired whenever an OrderCreated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'date',
        type: 'DateTime',
      },
      {
        name: 'instrumentIdentifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'OrderDeleted',
    displayName: 'Order Deleted',
    description:
      'An event of this type is fired whenever an OrderDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
    ],
  },
  {
    id: 'OrderUpdated',
    displayName: 'Order Updated',
    description:
      'An event of this type is fired whenever an OrderUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'code',
        type: 'String',
      },
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'date',
        type: 'DateTime',
      },
      {
        name: 'instrumentIdentifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'PortfolioCreated',
    displayName: 'Portfolio Created',
    description:
      'An event of this type is fired whenever a PortfolioCreated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
    ],
  },
  {
    id: 'PortfolioDeleted',
    displayName: 'Portfolio Deleted',
    description:
      'An event of this type is fired whenever a PortfolioDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
    ],
  },
  {
    id: 'PortfolioUpdated',
    displayName: 'Portfolio Updated',
    description:
      'An event of this type is fired whenever a PortfolioUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
    ],
  },
  {
    id: 'QuoteDeleted',
    displayName: 'Quote Deleted',
    description:
      'An event of this type is fired whenever a QuoteDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'field',
        type: 'String',
      },
      {
        name: 'instrumentId',
        type: 'String',
      },
      {
        name: 'instrumentIdType',
        type: 'String',
      },
      {
        name: 'priceSource',
        type: 'String',
      },
      {
        name: 'provider',
        type: 'String',
      },
      {
        name: 'quoteType',
        type: 'String',
      },
      {
        name: 'scope',
        type: 'String',
      },
    ],
  },
  {
    id: 'QuoteUpdated',
    displayName: 'Quote Updated',
    description:
      'An event of this type is fired whenever a QuoteUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'field',
        type: 'String',
      },
      {
        name: 'instrumentId',
        type: 'String',
      },
      {
        name: 'instrumentIdType',
        type: 'String',
      },
      {
        name: 'priceSource',
        type: 'String',
      },
      {
        name: 'provider',
        type: 'String',
      },
      {
        name: 'quoteType',
        type: 'String',
      },
      {
        name: 'scope',
        type: 'String',
      },
      {
        name: 'metricValue.Value',
        type: 'Decimal',
      },
      {
        name: 'metricValue.Unit',
        type: 'String',
      },
      {
        name: 'effectiveAt',
        type: 'DateTime',
      },
    ],
  },
  {
    id: 'TransactionCreated',
    displayName: 'Transaction Created',
    description:
      'An event of this type is fired whenever a TransactionCreated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'transactionId',
        type: 'String',
      },
      {
        name: 'transactionDate',
        type: 'DateTime',
      },
      {
        name: 'instrumentIdentifiers',
        type: 'CollectionOfIdentifiers',
      },
    ],
  },
  {
    id: 'TransactionDeleted',
    displayName: 'Transaction Deleted',
    description:
      'An event of this type is fired whenever a TransactionDeleted event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'transactionId',
        type: 'String',
      },
      {
        name: 'transactionDate',
        type: 'DateTime',
      },
    ],
  },
  {
    id: 'TransactionPortfolioCreated',
    displayName: 'Transaction Portfolio Created',
    description:
      'An event of this type is fired whenever a new transaction portfolio is created in LUSID',
    application: 'Lusid',
    headerSchema: [],
    bodySchema: [],
  },
  {
    id: 'TransactionUpdated',
    displayName: 'Transaction Updated',
    description:
      'An event of this type is fired whenever a TransactionUpdated event is created in LUSID',
    application: 'LUSID',
    headerSchema: [
      {
        name: 'eventType',
        type: 'String',
      },
      {
        name: 'requestId',
        type: 'String',
      },
      {
        name: 'userId',
        type: 'String',
      },
      {
        name: 'action',
        type: 'String',
      },
      {
        name: 'entityType',
        type: 'String',
      },
      {
        name: 'timestamp',
        type: 'DateTime',
      },
      {
        name: 'href',
        type: 'String',
      },
    ],
    bodySchema: [
      {
        name: 'portfolioScope',
        type: 'String',
      },
      {
        name: 'portfolioCode',
        type: 'String',
      },
      {
        name: 'transactionId',
        type: 'String',
      },
      {
        name: 'transactionDate',
        type: 'DateTime',
      },
    ],
  },
];

export const eventTypesByApplication: EventTypesByApplication = {
  Drive: [
    {
      id: 'FileContentVirusScanCompleted',
      displayName: 'File Content Virus Scan Completed',
      description:
        'An event of this type is fired whenever a FileContentVirusScanCompleted event is created in Drive',
      application: 'Drive',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'fileId',
          type: 'String',
        },
        {
          name: 'folderId',
          type: 'String',
        },
        {
          name: 'filePath',
          type: 'String',
        },
        {
          name: 'fileName',
          type: 'String',
        },
        {
          name: 'status',
          type: 'String',
        },
        {
          name: 'statusDetail',
          type: 'String',
        },
      ],
    },
    {
      id: 'FileCreated',
      displayName: 'File Created',
      description:
        'An event of this type is fired whenever a FileCreated event is created in Drive',
      application: 'Drive',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'fileId',
          type: 'String',
        },
        {
          name: 'folderId',
          type: 'String',
        },
        {
          name: 'filePath',
          type: 'String',
        },
        {
          name: 'fileName',
          type: 'String',
        },
        {
          name: 'status',
          type: 'String',
        },
        {
          name: 'statusDetail',
          type: 'String',
        },
      ],
    },
    {
      id: 'FileDeleted',
      displayName: 'File Deleted',
      description:
        'An event of this type is fired whenever a FileDeleted event is created in Drive',
      application: 'Drive',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'fileId',
          type: 'String',
        },
        {
          name: 'folderId',
          type: 'String',
        },
        {
          name: 'filePath',
          type: 'String',
        },
        {
          name: 'fileName',
          type: 'String',
        },
        {
          name: 'status',
          type: 'String',
        },
        {
          name: 'statusDetail',
          type: 'String',
        },
      ],
    },
    {
      id: 'FileMetadataUpdated',
      displayName: 'File Metadata Updated',
      description:
        'An event of this type is fired whenever a FileMetadataUpdated event is created in Drive',
      application: 'Drive',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'fileId',
          type: 'String',
        },
        {
          name: 'folderId',
          type: 'String',
        },
        {
          name: 'filePath',
          type: 'String',
        },
        {
          name: 'fileName',
          type: 'String',
        },
        {
          name: 'status',
          type: 'String',
        },
        {
          name: 'statusDetail',
          type: 'String',
        },
      ],
    },
    {
      id: 'FolderCreated',
      displayName: 'Folder Created',
      description:
        'An event of this type is fired whenever a FolderCreated event is created in Drive',
      application: 'Drive',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'folderId',
          type: 'String',
        },
        {
          name: 'folderPath',
          type: 'String',
        },
        {
          name: 'folderName',
          type: 'String',
        },
      ],
    },
    {
      id: 'FolderDeleted',
      displayName: 'Folder Deleted',
      description:
        'An event of this type is fired whenever a FolderDeleted event is created in Drive',
      application: 'Drive',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'folderId',
          type: 'String',
        },
        {
          name: 'folderPath',
          type: 'String',
        },
        {
          name: 'folderName',
          type: 'String',
        },
      ],
    },
    {
      id: 'FolderMetadataUpdated',
      displayName: 'Folder Metadata Updated',
      description:
        'An event of this type is fired whenever a FolderMetadataUpdated event is created in Drive',
      application: 'Drive',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'folderId',
          type: 'String',
        },
        {
          name: 'folderPath',
          type: 'String',
        },
        {
          name: 'folderName',
          type: 'String',
        },
      ],
    },
  ],
  Integrations: [
    {
      id: 'IntegrationRunEnded',
      displayName: 'Integration Run Ended',
      description:
        'An event of this type is fired whenever an IntegrationRunEnded event is created in Integrations',
      application: 'Integrations',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'runId',
          type: 'String',
        },
        {
          name: 'instanceId',
          type: 'String',
        },
        {
          name: 'integrationName',
          type: 'String',
        },
        {
          name: 'integrationType',
          type: 'String',
        },
        {
          name: 'status',
          type: 'String',
        },
      ],
    },
  ],
  LUSID: [
    {
      id: 'AllocationCreated',
      displayName: 'Allocation Created',
      description:
        'An event of this type is fired whenever an AllocationCreated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'code',
          type: 'String',
        },
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'date',
          type: 'DateTime',
        },
        {
          name: 'instrumentIdentifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'AllocationDeleted',
      displayName: 'Allocation Deleted',
      description:
        'An event of this type is fired whenever an AllocationDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'code',
          type: 'String',
        },
      ],
    },
    {
      id: 'AllocationUpdated',
      displayName: 'Allocation Updated',
      description:
        'An event of this type is fired whenever an AllocationUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'code',
          type: 'String',
        },
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'date',
          type: 'DateTime',
        },
        {
          name: 'instrumentIdentifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'ConstituentsUpdated',
      displayName: 'Constituents Updated',
      description:
        'An event of this type is fired whenever a ConstituentsUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'effectiveFrom',
          type: 'DateTime',
        },
      ],
    },
    {
      id: 'HoldingAdjustmentCreated',
      displayName: 'Holding Adjustment Created',
      description:
        'An event of this type is fired whenever a HoldingAdjustmentCreated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'effectiveAt',
          type: 'DateTime',
        },
      ],
    },
    {
      id: 'HoldingAdjustmentDeleted',
      displayName: 'Holding Adjustment Deleted',
      description:
        'An event of this type is fired whenever a HoldingAdjustmentDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'effectiveAt',
          type: 'DateTime',
        },
      ],
    },
    {
      id: 'HoldingAdjustmentUpdated',
      displayName: 'Holding Adjustment Updated',
      description:
        'An event of this type is fired whenever a HoldingAdjustmentUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'effectiveAt',
          type: 'DateTime',
        },
        {
          name: 'instrumentIdentifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'InstrumentCreated',
      displayName: 'Instrument Created',
      description:
        'An event of this type is fired whenever an InstrumentCreated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'lusidInstrumentId',
          type: 'String',
        },
        {
          name: 'identifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'InstrumentDeleted',
      displayName: 'Instrument Deleted',
      description:
        'An event of this type is fired whenever an InstrumentDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'lusidInstrumentId',
          type: 'String',
        },
        {
          name: 'identifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'InstrumentUpdated',
      displayName: 'Instrument Updated',
      description:
        'An event of this type is fired whenever an InstrumentUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'lusidInstrumentId',
          type: 'String',
        },
        {
          name: 'identifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'LegalEntityCreated',
      displayName: 'Legal Entity Created',
      description:
        'An event of this type is fired whenever a LegalEntityCreated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'identifiers',
          type: 'CollectionOfIdentifiers',
        },
        {
          name: 'lusidLegalEntityId',
          type: 'String',
        },
      ],
    },
    {
      id: 'LegalEntityDeleted',
      displayName: 'Legal Entity Deleted',
      description:
        'An event of this type is fired whenever a LegalEntityDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'identifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'LegalEntityUpdated',
      displayName: 'Legal Entity Updated',
      description:
        'An event of this type is fired whenever a LegalEntityUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'identifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'OrderCreated',
      displayName: 'Order Created',
      description:
        'An event of this type is fired whenever an OrderCreated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'code',
          type: 'String',
        },
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'date',
          type: 'DateTime',
        },
        {
          name: 'instrumentIdentifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'OrderDeleted',
      displayName: 'Order Deleted',
      description:
        'An event of this type is fired whenever an OrderDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'code',
          type: 'String',
        },
      ],
    },
    {
      id: 'OrderUpdated',
      displayName: 'Order Updated',
      description:
        'An event of this type is fired whenever an OrderUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'code',
          type: 'String',
        },
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'date',
          type: 'DateTime',
        },
        {
          name: 'instrumentIdentifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'PortfolioCreated',
      displayName: 'Portfolio Created',
      description:
        'An event of this type is fired whenever a PortfolioCreated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
      ],
    },
    {
      id: 'PortfolioDeleted',
      displayName: 'Portfolio Deleted',
      description:
        'An event of this type is fired whenever a PortfolioDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
      ],
    },
    {
      id: 'PortfolioUpdated',
      displayName: 'Portfolio Updated',
      description:
        'An event of this type is fired whenever a PortfolioUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
      ],
    },
    {
      id: 'QuoteDeleted',
      displayName: 'Quote Deleted',
      description:
        'An event of this type is fired whenever a QuoteDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'field',
          type: 'String',
        },
        {
          name: 'instrumentId',
          type: 'String',
        },
        {
          name: 'instrumentIdType',
          type: 'String',
        },
        {
          name: 'priceSource',
          type: 'String',
        },
        {
          name: 'provider',
          type: 'String',
        },
        {
          name: 'quoteType',
          type: 'String',
        },
        {
          name: 'scope',
          type: 'String',
        },
      ],
    },
    {
      id: 'QuoteUpdated',
      displayName: 'Quote Updated',
      description:
        'An event of this type is fired whenever a QuoteUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'field',
          type: 'String',
        },
        {
          name: 'instrumentId',
          type: 'String',
        },
        {
          name: 'instrumentIdType',
          type: 'String',
        },
        {
          name: 'priceSource',
          type: 'String',
        },
        {
          name: 'provider',
          type: 'String',
        },
        {
          name: 'quoteType',
          type: 'String',
        },
        {
          name: 'scope',
          type: 'String',
        },
        {
          name: 'metricValue.Value',
          type: 'Decimal',
        },
        {
          name: 'metricValue.Unit',
          type: 'String',
        },
        {
          name: 'effectiveAt',
          type: 'DateTime',
        },
      ],
    },
    {
      id: 'TransactionCreated',
      displayName: 'Transaction Created',
      description:
        'An event of this type is fired whenever a TransactionCreated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'transactionId',
          type: 'String',
        },
        {
          name: 'transactionDate',
          type: 'DateTime',
        },
        {
          name: 'instrumentIdentifiers',
          type: 'CollectionOfIdentifiers',
        },
      ],
    },
    {
      id: 'TransactionDeleted',
      displayName: 'Transaction Deleted',
      description:
        'An event of this type is fired whenever a TransactionDeleted event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'transactionId',
          type: 'String',
        },
        {
          name: 'transactionDate',
          type: 'DateTime',
        },
      ],
    },
    {
      id: 'TransactionUpdated',
      displayName: 'Transaction Updated',
      description:
        'An event of this type is fired whenever a TransactionUpdated event is created in LUSID',
      application: 'LUSID',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'portfolioScope',
          type: 'String',
        },
        {
          name: 'portfolioCode',
          type: 'String',
        },
        {
          name: 'transactionId',
          type: 'String',
        },
        {
          name: 'transactionDate',
          type: 'DateTime',
        },
      ],
    },
  ],
  Lusid: [
    {
      id: 'TransactionPortfolioCreated',
      displayName: 'Transaction Portfolio Created',
      description:
        'An event of this type is fired whenever a new transaction portfolio is created in LUSID',
      application: 'Lusid',
      headerSchema: [],
      bodySchema: [],
    },
  ],
  'Notification Service': [
    {
      id: 'Manual',
      displayName: 'Manual event',
      description:
        'Events of this type can be triggered manually by posting to the Trigger Manual Event API endpoint',
      application: 'Notification Service',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
      ],
      bodySchema: [
        {
          name: 'subject',
          type: 'String',
        },
        {
          name: 'message',
          type: 'DateTime',
        },
        {
          name: 'jsonMessage',
          type: 'JsonObject',
        },
      ],
    },
  ],
  Scheduler: [
    {
      id: 'JobDidNotStart',
      displayName: 'Job Did Not Start',
      description:
        'An event of this type is fired whenever a JobDidNotStart event is created in Scheduler',
      application: 'Scheduler',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scheduleScope',
          type: 'String',
        },
        {
          name: 'scheduleCode',
          type: 'String',
        },
        {
          name: 'jobScope',
          type: 'String',
        },
        {
          name: 'jobCode',
          type: 'String',
        },
        {
          name: 'runId',
          type: 'String',
        },
      ],
    },
    {
      id: 'JobFailed',
      displayName: 'Job Failed',
      description:
        'An event of this type is fired whenever a JobFailed event is created in Scheduler',
      application: 'Scheduler',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scheduleScope',
          type: 'String',
        },
        {
          name: 'scheduleCode',
          type: 'String',
        },
        {
          name: 'jobScope',
          type: 'String',
        },
        {
          name: 'jobCode',
          type: 'String',
        },
        {
          name: 'runId',
          type: 'String',
        },
      ],
    },
    {
      id: 'JobSucceeded',
      displayName: 'Job Succeeded',
      description:
        'An event of this type is fired whenever a JobSucceeded event is created in Scheduler',
      application: 'Scheduler',
      headerSchema: [
        {
          name: 'eventType',
          type: 'String',
        },
        {
          name: 'requestId',
          type: 'String',
        },
        {
          name: 'userId',
          type: 'String',
        },
        {
          name: 'action',
          type: 'String',
        },
        {
          name: 'entityType',
          type: 'String',
        },
        {
          name: 'timestamp',
          type: 'DateTime',
        },
        {
          name: 'href',
          type: 'String',
        },
      ],
      bodySchema: [
        {
          name: 'scheduleScope',
          type: 'String',
        },
        {
          name: 'scheduleCode',
          type: 'String',
        },
        {
          name: 'jobScope',
          type: 'String',
        },
        {
          name: 'jobCode',
          type: 'String',
        },
        {
          name: 'runId',
          type: 'String',
        },
      ],
    },
  ],
};

export const eventTypeById: Record<string, EventType> = eventTypes.reduce(
  (acc, eventType) => {
    acc[eventType.id] = eventType;
    return acc;
  },
  {} as Record<string, EventType>
);
